### ISSUE TITLE
Stuck on Authorizing....

### ISSUE THREAD

**Issue by hach3** [mb3364/Java-Twitch-Api-Wrapper#23]
Hello there, so i'm trying to use the twitch api for my java application. I can display games, channels etc. The problem happens when i try to use the authentication Implicit Grant Flow, i'm redirected to the authentication url, then to authorize.html. This page is stuck and my program too as 
boolean authSuccess = twitch.auth().awaitAccessToken(); is waiting for something that never comes i guess...

Here's my function 
`public static void connect()
	{
		Twitch twitch = new Twitch();
		twitch.setClientId("my client id");
		
	
		URI callbackUri = null;
		try {
			callbackUri = new URI("http://127.0.0.1:23522/authorize.html/");
		} catch (URISyntaxException e) {
			e.printStackTrace();
		}
		
		String authUrl = twitch.auth().getAuthenticationUrl(twitch.getClientId(), callbackUri, Scopes.USER_READ);
		System.out.println(authUrl);
		try {
			String url = authUrl + "&force_verify=true";
			java.awt.Desktop.getDesktop().browse(java.net.URI.create(url));
		} catch (java.io.IOException e) {
			System.out.println(e.getMessage());
		}
		
		boolean authSuccess = twitch.auth().awaitAccessToken();
	
		if (authSuccess) {
			  String accessToken = twitch.auth().getAccessToken();
			  System.out.println("Access Token: " + accessToken);
			  String name = twitch.auth().getClientId();
			  System.out.println("Client id:" + name);
			  
		} else {
			  System.out.println(twitch.auth().getAuthenticationError());
			 
		}
	}`

**Comment by hach3** [comment]
I just saw someone had the same issue. He corrected it by replacing the callback url by authorize.html, which i've done and it still doesn't work. 
Maybe i haven't understood how to manage authentication in java :s

**Comment by MaximKulikov** [comment]
http://127.0.0.1:23522/authorize.html
Does that exacly same URL u use when register twitch app?
