### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by s-tuna** [mb3364/Java-Twitch-Api-Wrapper#8]
despite my searching I have been unable to discover how to utilize your wrapper. If you could distribute it as a .jar, or provide a guide on how to utilize it, that would be much appreciated.

**Comment by Draygera** [comment]
@s-tuna I'm trying to figure this out myself. Except, I'm using gradle and trying to build it using the maven plugin. Keep running into the whole "repo not found thing" despite adding all of the info from the pom.xml file I can find. Got ideas?

**Comment by Draygera** [comment]
@s-tuna Update: If you are using gradle (which I would highly recommend, tbh), first you need to follow the instructions here: https://github.com/layerhq/gradle-git-repo-plugin/blob/master/README.md so that you can install the git-repo plugin into your project.

Then, you need to add this to your repositories section:

git("https://github.com/mb3364/Java-Twitch-Api-Wrapper.git", "com.mb3364.twitch", "master", "releases")

But, beyond that, I'm not sure what else can be done right now. It doesn't seem to compile the repo, just downloads it so far.

**Comment by Draygera** [comment]
@s-tuna Update 2: I've found a much better git plugin that is a whole lot easier to use: https://github.com/ajoberstar/grgit

Just make sure you follow the instructions for installing in the Readme.md file

Also, it's not documented in the Wiki file, but here's the easiest way to clone this git repository using tasks in your build.gradle file:

import org.ajoberstar.grgit.*

task clone << {
   def grgit = Grgit.clone(dir: 'path/to/where/you/want/git/repo', uri: 'https://github.com/mb3364/Java-Twitch-Api-Wrapper.git')
   def grgit1 = Grgit.clone(dir: 'path/to/where/you/want/git/repo', uri: 'https://github.com/mb3364/java-asynch-http.git') // this is another repo that is required for building the Twitch-Api-Wrapper
}

If you're using gradle, the next step is converting the pom.xml file in both repo directories to a build.gradle file by using 

gradle init

in those directories. It will create a new build.gradle file for each of the pom.xml files.

I was only able to successfully build the asynch-http-client but not the Twitch-Api-Wrapper, so your milage will vary.

**Comment by mb3364** [comment]
Hey, sorry for the delayed response. I have created a [release](https://github.com/mb3364/Java-Twitch-Api-Wrapper/releases/tag/0.3) that includes a downloadable jar without the dependencies included, as well as a jar with all the dependencies already included.

I also updated the readme for dependencies and install instructions. Please let me know if there is still confusion.

**Comment by Draygera** [comment]
No problem, @mb3364. I was just learning how to use gradle myself and was sharing some of what I found during my testing. Also, I'm currently working on building a custom bot and was looking for alternatives to what @Qkyrie was working on. Again, thanks for the response and I hope I didn't make a big mess of this issue. XD

**Comment by ChargingBulle** [comment]
downloadable release is good

but what about uploading it to the central maven repository?

**Comment by kolatra** [comment]
Uploading to central maven would be absolutely incredible.

**Comment by MaximKulikov** [comment]
Absolutely. I had to create own private repository coz it not in central, thats completely wrong

**Comment by Qkyrie** [comment]
Is the project still maintained? If not, how close is it to a working solution? I consider forking it to release it to maven central, keeping it up to date. @urgrue

**Comment by Gikkman** [comment]
I know someone forked this project and made it downloadable via jitpack.io, but I can't remember where that was...
